### ISSUE TITLE
General typo's ddosv5.0.2

### ISSUE THREAD

**Issue by pieterhouwen** [FreelancePentester/ddos-script#10]
Since I'm running into a few I'm just gonna post them here so I don't have to open an issue for every typo.

Line 2622 references a function installeyewitness on line 1296, but the function states installeyeSwitness.

**Comment by pieterhouwen** [comment]
Line 1307 states "cd /opt/EyeWitness-master/setup/" , needs to be "/opt/intelligence-gathering/WebApp/EyeWitness-master/setup/"

**Comment by pieterhouwen** [comment]
Line 1565 states git clone https://bitbucket.org/al14s/rawr.git /opt/intelligence-gathering/WebApp/rarw/

needs to be 

git clone https://bitbucket.org/al14s/rawr.git /opt/intelligence-gathering/WebApp/rawr/ (note the last two letters are switched)

**Comment by pieterhouwen** [comment]
Line 1039 states ./install.sh

needs to be 

cd /opt/BypassAV/the-backdoor-factory/ && ./install.sh

**Comment by FreelancePentester** [comment]
Thank you!
