### ISSUE TITLE
Virtualbox Problem (Solved)

### ISSUE THREAD

**Issue by cacaocaca** [FreelancePentester/ddos-script#4]
Linux kali 4.7.0-kali1-686-pae #1 SMP Debian 4.7.8-1kali1 (2016-10-24) i686 GNU/Linux
reposity
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
First i have try to install virtualbox normal with apt but i have the same error so i have remeber your video on youtube of this script so i have do try to install virtualbox with it but the problem is same 

The virtual machine 'windows7' has terminated unexpectedly during startup with exit code 1 (0x1).

Codice 'uscita: 
NS_ERROR_FAILURE (0x80004005)
Componente: 
MachineWrap
Interfaccia: 
IMachine {b2547866-a0a1-4391-8b86-6952d82efaa0}
-----------------------------------
Kernel driver not installed (rc=-1908)

The VirtualBox Linux kernel driver (vboxdrv) is either not loaded or there is a permission problem with /dev/vboxdrv. Please reinstall virtualbox-dkms package and load the kernel module by executing

'modprobe vboxdrv'

as root.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT.

**Comment by cacaocaca** [comment]
I have solved 
apt-get update && apt-get dist-upgrade -y
reboot
apt-get --purge remove virtualbox
apt-get install linux-headers-$(uname -r)
afther install virtualbox with your script

**Comment by FreelancePentester** [comment]
thanks. Because my script is for kernel 4.7.0. Latest kali linux kernel is 4.7.8
